kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: observability
nodes:
- role: control-plane
  image: kindest/node:v1.30.13
  extraPortMappings:
  - containerPort: 30000
    hostPort: 8080
  - containerPort: 30001
    hostPort: 8081
  - containerPort: 30002
    hostPort: 8082
  - containerPort: 30003
    hostPort: 8083
  - containerPort: 30004
    hostPort: 8084
  - containerPort: 30005
    hostPort: 8085
  - containerPort: 30006
    hostPort: 8086